apiVersion: v1
data:
  MONGO_DB: sharkinfo
  MONGO_PASSWORD: password
  MONGO_PORT: "27017"
  MONGO_USERNAME: ladymarg
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs-env
  name: nodejs-env
